### ISSUE TITLE
Install cmti files

### ISSUE THREAD

**Issue by dbuenzli** [johnwhitington/camlpdf#31]
Hello John, 

An `odig` user is reporting me that `camlpdf`'s doc strings are not showing up, and [indeed](https://b0-system.github.io/odig/doc@odig.dark/camlpdf/index.html) that is not the case. 

For `odig` to be able to do its work you need to generate `cmti` files by compiling with `-bin-annot` and install them alongside the `cmi` files. It would be nice if you started doing this.

There are a few other things that can be done like installing your readme and changes files in `$(opam var doc)/camlpdf/` so that they are linked from the package page and can be consulted via `odig {readme,changes}`. Installing the `opam` file in `$(opam var lib)` also makes things better. Full details about the packaging conventions are [here](https://b0-system.github.io/odig/doc@odig.dark/odig/packaging.html).

**Comment by johnwhitington** [comment]
I added `-bin-annot` to the native and bytecode flags, and cmt (I presume you meant cmt not cmti?) files to the install line, but I get:

```
Installing library with ocamlfind
ocamlfind install  camlpdf META camlpdf.a camlpdf.cma camlpdf.cmxa libcamlpdf_stubs.a dllcamlpdf_stubs.* pdfutil.mli pdfio.mli pdftransform.mli pdfunits.mli pdfpaper.mli pdfcryptprimitives.mli pdf.mli pdfcrypt.mli pdfflate.mli pdfcodec.mli pdfwrite.mli pdfgenlex.mli pdfread.mli pdfjpeg.mli pdfops.mli pdfdest.mli pdfmarks.mli pdfpagelabels.mli pdfpage.mli pdfannot.mli pdffun.mli pdfspace.mli pdfimage.mli pdfafm.mli pdfafmdata.mli pdfglyphlist.mli pdftext.mli pdfstandard14.mli pdfgraphics.mli pdfshapes.mli pdfdate.mli pdfocg.mli pdfcff.mli pdftype1.mli pdftruetype.mli pdftype0.mli pdfmerge.mli pdfutil.cmi pdfio.cmi pdftransform.cmi pdfunits.cmi pdfpaper.cmi pdfcryptprimitives.cmi pdf.cmi pdfcrypt.cmi pdfflate.cmi pdfcodec.cmi pdfwrite.cmi pdfgenlex.cmi pdfread.cmi pdfjpeg.cmi pdfops.cmi pdfdest.cmi pdfmarks.cmi pdfpagelabels.cmi pdfpage.cmi pdfannot.cmi pdffun.cmi pdfspace.cmi pdfimage.cmi pdfafm.cmi pdfafmdata.cmi pdfglyphlist.cmi pdftext.cmi pdfstandard14.cmi pdfgraphics.cmi pdfshapes.cmi pdfdate.cmi pdfocg.cmi pdfcff.cmi pdftype1.cmi pdftruetype.cmi pdftype0.cmi pdfmerge.cmi pdfutil.cmt pdfio.cmt pdftransform.cmt pdfunits.cmt pdfpaper.cmt pdfcryptprimitives.cmt pdf.cmt pdfcrypt.cmt pdfflate.cmt pdfcodec.cmt pdfwrite.cmt pdfgenlex.cmt pdfread.cmt pdfjpeg.cmt pdfops.cmt pdfdest.cmt pdfmarks.cmt pdfpagelabels.cmt pdfpage.cmt pdfannot.cmt pdffun.cmt pdfspace.cmt pdfimage.cmt pdfafm.cmt pdfafmdata.cmt pdfglyphlist.cmt pdftext.cmt pdfstandard14.cmt pdfgraphics.cmt pdfshapes.cmt pdfdate.cmt pdfocg.cmt pdfcff.cmt pdftype1.cmt pdftruetype.cmt pdftype0.cmt pdfmerge.cmt pdfutil.cmx pdfio.cmx pdftransform.cmx pdfunits.cmx pdfpaper.cmx pdfcryptprimitives.cmx pdf.cmx pdfcrypt.cmx pdfflate.cmx pdfcodec.cmx pdfwrite.cmx pdfgenlex.cmx pdfread.cmx pdfjpeg.cmx pdfops.cmx pdfdest.cmx pdfmarks.cmx pdfpagelabels.cmx pdfpage.cmx pdfannot.cmx pdffun.cmx pdfspace.cmx pdfimage.cmx pdfafm.cmx pdfafmdata.cmx pdfglyphlist.cmx pdftext.cmx pdfstandard14.cmx pdfgraphics.cmx pdfshapes.cmx pdfdate.cmx pdfocg.cmx pdfcff.cmx pdftype1.cmx pdftruetype.cmx pdftype0.cmx pdfmerge.cmx
ocamlfind: Conflict with file: /Users/john/.opam/4.07.1/lib/camlpdf/pdfmerge.cmx
make: *** [libinstall] Error 2
```

Any ideas?

**Comment by johnwhitington** [comment]
Never mind... this appears to have been a transient error. I have it working now....

**Comment by johnwhitington** [comment]
I have committed this. Version v2.3 of camlpdf and cpdf will be frozen next week, and I will do the rest of the work regarding OPAM changes when I update the OPAM packages.

**Comment by dbuenzli** [comment]
> I added `-bin-annot` to the native and bytecode flags, and cmt (I presume you meant cmt not cmti?) files to the install line,

No I mean `cmti` files.

**Comment by johnwhitington** [comment]
Ok, Fixed.

**Comment by dbuenzli** [comment]
It seems the cmti files are still not installed. Here on macos:
```
> opam list --installed | grep camlpdf   
camlpdf               2.5.3       Read, write and modify PDF files
> ls $(opam var camlpdf:lib) | grep .cmti
```

This means that none of your doc string shows up in `odig` generated docsets nor on the [ocaml documentation website](https://ocaml.org/p/camlpdf/latest/doc/Pdf/index.html).

**Comment by johnwhitington** [comment]
Fixed now.
